apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin
rules:
- apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
  resources: ["pods", "services", "deployments", "roles", "rolebindings", "namespaces"]
  verbs: ["*"]