apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-viewer-bindings
subjects:
- kind: Group
  name: security-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-viewer
  apiGroup: rbac.authorization.k8s.io

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-bindings
subjects:
- kind: Group
  name: developer
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: analytic
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: product-owner
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viewer
  apiGroup: rbac.authorization.k8s.io

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-bindings
subjects:
- kind: Group
  name: devops
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: sre
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io